name: Security Issue
description: Bring attention to a security issue in the project
title: "[SECURITY] "
labels: ["priority","security"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the issue is
      placeholder: Tell us what's wrong
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Offending Code
      description: What are the offendinng code snippets/functions?
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant info, logs, screenshots, etc.
      placeholder: Add any other context about the problem here
